# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 530)
        current_dir = os.path.dirname(os.path.realpath(__file__))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.label.setText("")
        d_path = os.path.join(current_dir, "imagenes/campus.png")
        self.label.setPixmap(QtGui.QPixmap(d_path))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 361, 531))
        self.label_2.setMouseTracking(False)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(690, 10, 221, 100))
        self.label_3.setText("")
        d_path = os.path.join(current_dir, "imagenes/descarga.png")
        self.label_3.setPixmap(QtGui.QPixmap(d_path))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(750, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(640, 170, 51, 51))
        self.label_5.setText("")
        d_path = os.path.join(current_dir, "imagenes/usuario.png")
        self.label_5.setPixmap(QtGui.QPixmap(d_path))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(640, 240, 61, 61))
        self.label_6.setText("")
        d_path=  os.path.join(current_dir, "imagenes/contrasena.png")
        self.label_6.setPixmap(QtGui.QPixmap(d_path))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.txt_user = QtWidgets.QLineEdit(parent=Form)
        self.txt_user.setGeometry(QtCore.QRect(700, 200, 221, 22))
        self.txt_user.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.txt_user.setText("")
        self.txt_user.setObjectName("txt_user")
        self.txt_contrasena = QtWidgets.QLineEdit(parent=Form)
        self.txt_contrasena.setGeometry(QtCore.QRect(700, 270, 221, 22))
        self.txt_contrasena.setText("")
        self.txt_contrasena.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_contrasena.setObjectName("txt_contrasena")
        self.btn_ingresar = QtWidgets.QPushButton(parent=Form)
        self.btn_ingresar.setGeometry(QtCore.QRect(750, 340, 93, 28))
        self.btn_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_ingresar.setStyleSheet("background-color: rgb(169, 169, 169);\n""border-radius:5px;")
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(700, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Login"))
        self.btn_ingresar.setText(_translate("Form", "Ingresar"))
        self.label_8.setText(_translate("Form", "Reserva LAB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
