# Form implementation generated from reading ui file 'reservalaboratorios.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(967, 590)
        current_dir = os.path.dirname(os.path.realpath(__file__))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, -20, 981, 621))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 220, 91))
        self.label_3.setText("")
        c_path = os.path.join(current_dir, "imagenes/descarga.png")
        self.label_3.setPixmap(QtGui.QPixmap(c_path))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 250, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_regresar = QtWidgets.QPushButton(parent=Form)
        self.btn_regresar.setEnabled(True)
        self.btn_regresar.setGeometry(QtCore.QRect(850, 10, 81, 61))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_regresar.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(1, 106, 127);\n"
"")
        icon = QtGui.QIcon()
        d_path = os.path.join(current_dir, "imagenes/hacia-atras.png")
        icon.addPixmap(QtGui.QPixmap(d_path), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setCheckable(False)
        self.btn_regresar.setObjectName("btn_regresar")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(80, 140, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cbox_laboratorios = QtWidgets.QComboBox(parent=Form)
        self.cbox_laboratorios.setGeometry(QtCore.QRect(80, 160, 341, 22))
        self.cbox_laboratorios.setObjectName("cbox_laboratorios")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(80, 190, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(80, 430, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.timeEdit_hora = QtWidgets.QTimeEdit(parent=Form)
        self.timeEdit_hora.setGeometry(QtCore.QRect(80, 450, 118, 22))
        self.timeEdit_hora.setObjectName("timeEdit_hora")
        self.btn_reservar = QtWidgets.QPushButton(parent=Form)
        self.btn_reservar.setGeometry(QtCore.QRect(80, 500, 92, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.btn_reservar.setFont(font)
        self.btn_reservar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_reservar.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"border-radius:5px;")
        self.btn_reservar.setObjectName("btn_reservar")
        self.btn_cancelar = QtWidgets.QPushButton(parent=Form)
        self.btn_cancelar.setGeometry(QtCore.QRect(200, 500, 92, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_cancelar.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"border-radius:5px;")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setGeometry(QtCore.QRect(80, 210, 471, 211))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Reservar Laboratorio"))
        self.btn_regresar.setText(_translate("Form", "Regresar"))
        self.label_8.setText(_translate("Form", "Selecione el laboratorio para su reserva:"))
        self.label_9.setText(_translate("Form", "Selecione la fecha de la reserva:"))
        self.label_10.setText(_translate("Form", "Selecione la hora de la reserva"))
        self.btn_reservar.setText(_translate("Form", "Reservar"))
        self.btn_cancelar.setText(_translate("Form", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
