# Form implementation generated from reading ui file 'acercade.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Acerca de")
        Form.resize(1000, 810)
        current_dir = os.path.dirname(os.path.realpath(__file__))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1111, 811))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 201, 811))
        self.label_2.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(220, 220, 771, 561))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(530, 10, 211, 81))
        self.label_4.setText("")
        c_path = os.path.join(current_dir, "imagenes/descarga.png")
        self.label_4.setPixmap(QtGui.QPixmap(c_path))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(600, 80, 71, 81))
        self.label_5.setText("")
        d_path = os.path.join(current_dir, "imagenes/acerca-de.png")
        self.label_5.setPixmap(QtGui.QPixmap(d_path))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(240, 140, 71, 81))
        self.label_6.setText("")
        d_path = os.path.join(current_dir, "imagenes/grupo.png")
        self.label_6.setPixmap(QtGui.QPixmap(d_path))
        self.label_6.setObjectName("label_6")
        self.btn_regresar = QtWidgets.QPushButton(parent=Form)
        self.btn_regresar.setEnabled(True)
        self.btn_regresar.setGeometry(QtCore.QRect(890, 10, 81, 61))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_regresar.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(1, 106, 127);\n"
"")
        icon = QtGui.QIcon()
        d_path = os.path.join(current_dir, "imagenes/hacia-atras.png")
        icon.addPixmap(QtGui.QPixmap(d_path), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setCheckable(False)
        self.btn_regresar.setObjectName("btn_regresar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Reserva Lab v1.0.0\n"
"\n"
"Descripción:\n"
"Reserva Lab es una aplicación diseñada para facilitar la reserva de laboratorios\n"
" en entornos académicos. Permite a docentes y estudiantes realizar reservas de laboratorios.\n"
"\n"
"Desarrolladores:\n"
"- Darwin Chuqui\n"
"\n"
"Créditos:\n"
"- https://www.flaticon.es/\n"
"\n"
"Notas de la Versión:\n"
"v1.0.0 (Fecha de lanzamiento: 15 de diciembre de 2023)\n"
"- Funcionalidad de reserva de laboratorios implementada.\n"
"- Mejoras en la interfaz de usuario.\n"
"- Correcciones de errores menores.\n"
"\n"
"Contacto:\n"
"Para asistencia y comentarios, contáctenos en support@reservalab.com\n"
"\n"
"¡Gracias por usar Reserva Lab!\n"
""))
        self.btn_regresar.setText(_translate("Form", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
