import os
from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 622)
        current_dir = os.path.dirname(os.path.realpath(__file__))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 981, 623))
        self.label.setText("")
        d_path = os.path.join(current_dir, "imagenes/campus2.png")
        self.label.setPixmap(QtGui.QPixmap(d_path))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.btn_regresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_regresar.setEnabled(True)
        self.btn_regresar.setGeometry(QtCore.QRect(820, 35, 81, 61))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_regresar.setStyleSheet("border-radius:5px;\n""background-color: rgb(1, 106, 127);\n""")
        icon = QtGui.QIcon()
        d_path = os.path.join(current_dir, "imagenes/hacia-atras.png")
        icon.addPixmap(QtGui.QPixmap(d_path), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setCheckable(False)
        self.btn_regresar.setObjectName("btn_regresar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuGestionar = QtWidgets.QMenu(parent=self.menuBar)
        self.menuGestionar.setObjectName("menuGestionar")
        self.menuReservar = QtWidgets.QMenu(parent=self.menuBar)
        self.menuReservar.setObjectName("menuReservar")
        self.menuVer = QtWidgets.QMenu(parent=self.menuBar)
        self.menuVer.setObjectName("menuVer")
        self.menuReportes = QtWidgets.QMenu(parent=self.menuBar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuAcerca_de = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")

        self.actionGestionUsuarios = QtGui.QAction(parent=MainWindow)
        self.actionGestionUsuarios.setObjectName("actionGestionUsuarios")
        self.actionGestionUsuarios.setToolTip("Gestión de Usuarios")
        self.actionGestionLaboratorios = QtGui.QAction(parent=MainWindow)
        self.actionGestionLaboratorios.setObjectName("actionGestionLaboratorios")
        self.actionSolicitudes = QtGui.QAction(parent=MainWindow)
        self.actionSolicitudes.setObjectName("actionSolicitudes")
        self.actionReservarLaboratorios = QtGui.QAction(parent=MainWindow)
        self.actionReservarLaboratorios.setObjectName("actionReservarLaboratorios")
        self.actionHorario_de_Laboratorio = QtGui.QAction(parent=MainWindow)
        self.actionHorario_de_Laboratorio.setObjectName("actionHorario_de_Laboratorio")
        self.actionReportesLaboratorios = QtGui.QAction(parent=MainWindow)
        self.actionReportesLaboratorios.setObjectName("actionReportesLaboratorios")
        self.actionReportesUsuarios = QtGui.QAction(parent=MainWindow)
        self.actionReportesUsuarios.setObjectName("actionReportesUsuarios")
        self.actionInformacion = QtGui.QAction(parent=MainWindow)
        self.actionInformacion.setObjectName("actionInformacion")

        self.menuGestionar.addSeparator()
        self.menuGestionar.addAction(self.actionGestionUsuarios)
        self.menuGestionar.addSeparator()
        self.menuGestionar.addAction(self.actionGestionLaboratorios)
        self.menuGestionar.addSeparator()
        self.menuGestionar.addAction(self.actionSolicitudes)

        self.menuReservar.addSeparator()
        self.menuReservar.addAction(self.actionReservarLaboratorios)
        self.menuVer.addSeparator()
        self.menuVer.addAction(self.actionHorario_de_Laboratorio)

        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionReportesLaboratorios)
        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionReportesUsuarios)

        self.menuAcerca_de.addSeparator()
        self.menuAcerca_de.addAction(self.actionInformacion)

        self.menuBar.addAction(self.menuGestionar.menuAction())
        self.menuBar.addAction(self.menuReservar.menuAction())
        self.menuBar.addAction(self.menuVer.menuAction())
        self.menuBar.addAction(self.menuReportes.menuAction())
        self.menuBar.addAction(self.menuAcerca_de.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_regresar.setText(_translate("MainWindow", "Regresar"))
        self.menuGestionar.setTitle(_translate("MainWindow", "Gestionar"))
        self.menuReservar.setTitle(_translate("MainWindow", "Reservar"))
        self.menuVer.setTitle(_translate("MainWindow", "Ver "))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
        self.actionGestionUsuarios.setText(_translate("MainWindow", "Usuarios"))
        self.actionGestionLaboratorios.setText(_translate("MainWindow", "Laboratorios"))
        self.actionReservarLaboratorios.setText(_translate("MainWindow", "Laboratorio"))
        self.actionInformacion.setText(_translate("MainWindow", "Informacion General"))
        self.actionHorario_de_Laboratorio.setText(_translate("MainWindow", "Horarios de laboratorios"))
        self.actionReportesLaboratorios.setText(_translate("MainWindow", "Laboratorio mas reservado"))
        self.actionReportesUsuarios.setText(_translate("MainWindow", "Laboratorios Usados"))
        self.actionSolicitudes.setText(_translate("MainWindow", "Solicitudes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
